---
  - apt:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items:
      - { name: "fail2ban",           state: "{{ fail2ban_version }}" }
      - { name: "{{ fail2ban_mta }}", state: "present" }
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    notify: start_fail2ban

  - yum:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items:
      - { name: "fail2ban",           state: "{{ fail2ban_version }}" }
      - { name: "{{ fail2ban_mta }}", state: "present" }
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    notify: start_fail2ban