---
  - apt:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items:
      - { name: "fail2ban", state: "absent" }
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    notify: start_fail2ban

  - yum:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items:
      - { name: "fail2ban", state: "absent" }
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    notify: start_fail2ban